/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WeatherLazyImport = createFileRoute('/weather')()
const PlantsLazyImport = createFileRoute('/plants')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WeatherLazyRoute = WeatherLazyImport.update({
  path: '/weather',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/weather.lazy').then((d) => d.Route))

const PlantsLazyRoute = PlantsLazyImport.update({
  path: '/plants',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/plants.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/plants': {
      preLoaderRoute: typeof PlantsLazyImport
      parentRoute: typeof rootRoute
    }
    '/weather': {
      preLoaderRoute: typeof WeatherLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  PlantsLazyRoute,
  WeatherLazyRoute,
])

/* prettier-ignore-end */
