name: 'CI'
on:
  workflow_dispatch:
  push:
    branches:
     - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  stack-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup action
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup pnpm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '/notes'
      - name: Install dependencies
        run: pnpm install

        #     - name: Lint
        # run: npm lint
        # working-directory: ./notes